#!/bin/bash
sudo apt update

# // install snapd
sudo apt install snapd

# // install certbot
sudo snap install --classic certbot
sudo certbot certonly --standalone -d mm.5q1a.multiportaio.fun --staple-ocsp -m barudo41@gmail.com --agree-tos

# // renew
sudo certbot renew --dry-run
sudo certbot renew
0     *     *     *     *      sudo certbot renew

# // delete certbot
sudo certbot delete
sudo certbot delete --cert-name mm.5q1a.multiportaio.fun
