#!/bin/bash
# (C) Copyright 2021-2022
# ==================================================================
# Name        : VPN Script Quick Installation Script
# Base        : HanSapa
# Mod By      :"""'''
# ==================================================================

# // Export Color & Information
export RED='\033[0;31m';
export GREEN='\033[0;32m';
export LIGHT='\033[0;37m';
export YELLOW='\033[0;33m';
export NC='\033[0m';

# // Export Banner Status Information
export ERROR="[${RED} ERROR ${NC}]";
export INFO="[${YELLOW} INFO ${NC}]";
export OKEY="[${GREEN} OKEY ${NC}]";

# // Exporting maklumat rangkaian
export IP_INFO_API=$( curl -s http://ip-api.com/json );

# // 1 is using ip-api
cat <<EOF > root/ip-detail.txt
IP='$( echo ${IP_INFO_API} | jq -r '.query' )'
ASN='$( echo ${IP_INFO_API} | jq -r '.as' | cut -d " " -f 2 )'
ISP='$( echo ${IP_INFO_API} | jq -r '.as' | cut -d " " -f 2-100 )'
REGIONAME='$( echo ${IP_INFO_API} | jq -r '.regionName' )'
REGION='$( echo ${IP_INFO_API} | jq -r '.regionName' )'
CITY='$( echo ${IP_INFO_API} | jq -r '.city' )'
COUNTRY='$( echo ${IP_INFO_API} | jq -r '.country' )'
COUNTRYCODE='$( echo ${IP_INFO_API} | jq -r '.countryCode' )'
TIMEZONE='$( echo ${IP_INFO_API} | jq -r '.timezone' )'
EOF
