[Baru buat]
type = drive
scope = drive
token = {"access_token":"ya29.a0ARrdaM8L1whJAH0RsqvHD1woPqyGVgw10mWzKE2OAVuReQqHCoaq6BOdy6OOhjt-D8yrbZ3pOhnkt1_hxmYr9ygghDBK9qPtdM5CG2JSVpC0ygy97Lo4B2gH6xlkfTBKVLhsDmJSVahNS54CVAd9LiaUpwq_","token_type":"Bearer","refresh_token":"1//0g0L1czu2sjcwCgYIARAAGBASNwF-L9IrXsswsWqZtNbK07-KzmE-SskB2KfxMJ01Zk1DDxlGSfrwKk_qzy3-JIXZZ2xGhh3F9_g","expiry":"2022-06-19T05:53:45.628468094Z"}
team_drive =
