#!/bin/bash
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0;37m'
bd='\e[1m'

clear
figlet VNSTAT | lolcat -d 5
echo -e ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${RED}          • BANDWITH MONITOR •          ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
echo -e "     [${CYAN}•1${NC}] $bd Lihat Total Bandwith Tersisa"
echo -e "     [${CYAN}•2${NC}] $bd Tabel Penggunaan Setiap 5 Menit"
echo -e "     [${CYAN}•3${NC}] $bd Tabel Penggunaan Setiap Jam"
echo -e "     [${CYAN}•4${NC}] $bd Tabel Penggunaan Setiap Hari"
echo -e "     [${CYAN}•5${NC}] $bd Tabel Penggunaan Setiap Bulan"
echo -e "     [${CYAN}•6${NC}] $bd Tabel Penggunaan Setiap Tahun"
echo -e "     [${CYAN}•7${NC}] $bd Tabel Penggunaan Tertinggi"
echo -e "     [${CYAN}•8${NC}] $bd Statistik Penggunaan Setiap Jam"
echo -e "     [${CYAN}•9${NC}] $bd Lihat Penggunaan Aktif Saat Ini"
echo -e "     [${CYAN}10${NC}] $bd Lihat Trafik Penggunaan Aktif Saat Ini [5s]"
echo -e ""
echo -e "     [${RED}•x${NC}] ${RED} Menu${NC}"
echo -e ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
read -p "  Please Enter The Number  [1-10 or x] :  "  menu
echo -e ""
clear
case $menu in
1)
figlet VNSTAT | lolcat -d 5
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${RED}        • TOTAL BANDWITH SERVER LEFT •          ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""

vnstat

echo -e ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
;;

2)
figlet VNSTAT | lolcat -d 5
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${RED}       • USE BANDWITH EVERY 5 MINUTES •          ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""

vnstat -5

echo -e ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
;;

3)
figlet VNSTAT | lolcat -d 5
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${RED}       • USE BANDWITH EVERY HOUR •          ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""

vnstat -h

echo -e ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
;;

4)
figlet VNSTAT | lolcat -d 5
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${RED}       • USE BANDWITH EVERY DAY •          ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""

vnstat -d

echo -e ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
;;

5)
figlet VNSTAT | lolcat -d 5
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${RED}       • USE BANDWITH EVERY MONTH •          ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""

vnstat -m

echo -e ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
;;

6)
figlet VNSTAT | lolcat -d 5
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${RED}       • USE BANDWITH EVERY YEARS •          ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""

vnstat -y

echo -e ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
;;

7)
figlet VNSTAT | lolcat -d 5
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${RED}          • HIGHEST BANDWITH USE •          ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""

vnstat -t

echo -e ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
;;

8)
figlet VNSTAT | lolcat -d 5
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${RED}   • BANDWITH GRAPHICS USED EVERY HOUR •          ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""

vnstat -hg

echo -e ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
;;

9)
figlet VNSTAT | lolcat -d 5
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${RED}      • LIVE USE OF BANDWITH CURRENTLY •          ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
echo -e " ${white}CTRL+C Untuk Keluar!${off}"
echo -e ""

vnstat -l

echo -e ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
;;

10)
figlet VNSTAT | lolcat -d 5
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${RED}      • LIVE TRAFFIC USE BANDWITH •          ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""

vnstat -tr

echo -e ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
;;

x)
sleep 1
menu
;;

*)
sleep 1
echo "Masukkan Nomor Yang Ada
bw
;;
esac
